package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Attendance generated by hbm2java
 */
public class Attendance  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile generalUserProfile;
     private Date date;
     private Date inTime;
     private Date outTime;
     private Boolean isMarked;

    public Attendance() {
    }

	
    public Attendance(GeneralUserProfile generalUserProfile, Date date, Date inTime) {
        this.generalUserProfile = generalUserProfile;
        this.date = date;
        this.inTime = inTime;
    }
    public Attendance(GeneralUserProfile generalUserProfile, Date date, Date inTime, Date outTime, Boolean isMarked) {
       this.generalUserProfile = generalUserProfile;
       this.date = date;
       this.inTime = inTime;
       this.outTime = outTime;
       this.isMarked = isMarked;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getInTime() {
        return this.inTime;
    }
    
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }
    public Date getOutTime() {
        return this.outTime;
    }
    
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }
    public Boolean getIsMarked() {
        return this.isMarked;
    }
    
    public void setIsMarked(Boolean isMarked) {
        this.isMarked = isMarked;
    }




}


