package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClaimApprovalType generated by hbm2java
 */
public class ClaimApprovalType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set claimApprovals = new HashSet(0);

    public ClaimApprovalType() {
    }

    public ClaimApprovalType(String name, Set claimApprovals) {
       this.name = name;
       this.claimApprovals = claimApprovals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getClaimApprovals() {
        return this.claimApprovals;
    }
    
    public void setClaimApprovals(Set claimApprovals) {
        this.claimApprovals = claimApprovals;
    }




}


