package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClaimType generated by hbm2java
 */
public class ClaimType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set claimItemses = new HashSet(0);

    public ClaimType() {
    }

    public ClaimType(String name, Set claimItemses) {
       this.name = name;
       this.claimItemses = claimItemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getClaimItemses() {
        return this.claimItemses;
    }
    
    public void setClaimItemses(Set claimItemses) {
        this.claimItemses = claimItemses;
    }




}


