package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Claims generated by hbm2java
 */
public class Claims  implements java.io.Serializable {


     private Integer id;
     private ClaimStatus claimStatus;
     private Employee employee;
     private Date addedDate;
     private Double totalAmount;
     private String note;
     private Boolean status;
     private Set claimApprovals = new HashSet(0);
     private Set claimItemses = new HashSet(0);
     private Set hrClaimApproves = new HashSet(0);

    public Claims() {
    }

	
    public Claims(ClaimStatus claimStatus, Employee employee) {
        this.claimStatus = claimStatus;
        this.employee = employee;
    }
    public Claims(ClaimStatus claimStatus, Employee employee, Date addedDate, Double totalAmount, String note, Boolean status, Set claimApprovals, Set claimItemses, Set hrClaimApproves) {
       this.claimStatus = claimStatus;
       this.employee = employee;
       this.addedDate = addedDate;
       this.totalAmount = totalAmount;
       this.note = note;
       this.status = status;
       this.claimApprovals = claimApprovals;
       this.claimItemses = claimItemses;
       this.hrClaimApproves = hrClaimApproves;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ClaimStatus getClaimStatus() {
        return this.claimStatus;
    }
    
    public void setClaimStatus(ClaimStatus claimStatus) {
        this.claimStatus = claimStatus;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getClaimApprovals() {
        return this.claimApprovals;
    }
    
    public void setClaimApprovals(Set claimApprovals) {
        this.claimApprovals = claimApprovals;
    }
    public Set getClaimItemses() {
        return this.claimItemses;
    }
    
    public void setClaimItemses(Set claimItemses) {
        this.claimItemses = claimItemses;
    }
    public Set getHrClaimApproves() {
        return this.hrClaimApproves;
    }
    
    public void setHrClaimApproves(Set hrClaimApproves) {
        this.hrClaimApproves = hrClaimApproves;
    }




}


