package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ClaimItems generated by hbm2java
 */
public class ClaimItems  implements java.io.Serializable {


     private Integer id;
     private ClaimType claimType;
     private Claims claims;
     private Double amount;
     private String attachment;
     private Date billdDate;

    public ClaimItems() {
    }

	
    public ClaimItems(ClaimType claimType, Claims claims) {
        this.claimType = claimType;
        this.claims = claims;
    }
    public ClaimItems(ClaimType claimType, Claims claims, Double amount, String attachment, Date billdDate) {
       this.claimType = claimType;
       this.claims = claims;
       this.amount = amount;
       this.attachment = attachment;
       this.billdDate = billdDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ClaimType getClaimType() {
        return this.claimType;
    }
    
    public void setClaimType(ClaimType claimType) {
        this.claimType = claimType;
    }
    public Claims getClaims() {
        return this.claims;
    }
    
    public void setClaims(Claims claims) {
        this.claims = claims;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }
    public Date getBilldDate() {
        return this.billdDate;
    }
    
    public void setBilldDate(Date billdDate) {
        this.billdDate = billdDate;
    }




}


