package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClaimStatus generated by hbm2java
 */
public class ClaimStatus  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set claimses = new HashSet(0);

    public ClaimStatus() {
    }

    public ClaimStatus(String name, Set claimses) {
       this.name = name;
       this.claimses = claimses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getClaimses() {
        return this.claimses;
    }
    
    public void setClaimses(Set claimses) {
        this.claimses = claimses;
    }




}


