package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ClaimApproval generated by hbm2java
 */
public class ClaimApproval  implements java.io.Serializable {


     private Integer id;
     private ClaimApprovalType claimApprovalType;
     private Claims claims;
     private Employee employee;
     private Date approvedDate;

    public ClaimApproval() {
    }

	
    public ClaimApproval(ClaimApprovalType claimApprovalType, Claims claims, Employee employee) {
        this.claimApprovalType = claimApprovalType;
        this.claims = claims;
        this.employee = employee;
    }
    public ClaimApproval(ClaimApprovalType claimApprovalType, Claims claims, Employee employee, Date approvedDate) {
       this.claimApprovalType = claimApprovalType;
       this.claims = claims;
       this.employee = employee;
       this.approvedDate = approvedDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ClaimApprovalType getClaimApprovalType() {
        return this.claimApprovalType;
    }
    
    public void setClaimApprovalType(ClaimApprovalType claimApprovalType) {
        this.claimApprovalType = claimApprovalType;
    }
    public Claims getClaims() {
        return this.claims;
    }
    
    public void setClaims(Claims claims) {
        this.claims = claims;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }




}


