package Model.Mapping;
// Generated May 21, 2024 8:03:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CommentsManager generated by hbm2java
 */
public class CommentsManager  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile generalUserProfile;
     private ProjectEmployees projectEmployees;
     private ProjectTasks projectTasks;
     private Projects projects;
     private String comment;
     private Date addedDate;

    public CommentsManager() {
    }

	
    public CommentsManager(GeneralUserProfile generalUserProfile, ProjectTasks projectTasks, Projects projects, String comment, Date addedDate) {
        this.generalUserProfile = generalUserProfile;
        this.projectTasks = projectTasks;
        this.projects = projects;
        this.comment = comment;
        this.addedDate = addedDate;
    }
    public CommentsManager(GeneralUserProfile generalUserProfile, ProjectEmployees projectEmployees, ProjectTasks projectTasks, Projects projects, String comment, Date addedDate) {
       this.generalUserProfile = generalUserProfile;
       this.projectEmployees = projectEmployees;
       this.projectTasks = projectTasks;
       this.projects = projects;
       this.comment = comment;
       this.addedDate = addedDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public ProjectEmployees getProjectEmployees() {
        return this.projectEmployees;
    }
    
    public void setProjectEmployees(ProjectEmployees projectEmployees) {
        this.projectEmployees = projectEmployees;
    }
    public ProjectTasks getProjectTasks() {
        return this.projectTasks;
    }
    
    public void setProjectTasks(ProjectTasks projectTasks) {
        this.projectTasks = projectTasks;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }




}


