package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set generalOrganizationProfiles = new HashSet(0);
     private Set generalUserProfiles = new HashSet(0);

    public Country() {
    }

    public Country(String name, Set generalOrganizationProfiles, Set generalUserProfiles) {
       this.name = name;
       this.generalOrganizationProfiles = generalOrganizationProfiles;
       this.generalUserProfiles = generalUserProfiles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getGeneralOrganizationProfiles() {
        return this.generalOrganizationProfiles;
    }
    
    public void setGeneralOrganizationProfiles(Set generalOrganizationProfiles) {
        this.generalOrganizationProfiles = generalOrganizationProfiles;
    }
    public Set getGeneralUserProfiles() {
        return this.generalUserProfiles;
    }
    
    public void setGeneralUserProfiles(Set generalUserProfiles) {
        this.generalUserProfiles = generalUserProfiles;
    }




}


