package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CredentialRoles generated by hbm2java
 */
public class CredentialRoles  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set userCredentialRoles = new HashSet(0);

    public CredentialRoles() {
    }

	
    public CredentialRoles(String name) {
        this.name = name;
    }
    public CredentialRoles(String name, Set userCredentialRoles) {
       this.name = name;
       this.userCredentialRoles = userCredentialRoles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserCredentialRoles() {
        return this.userCredentialRoles;
    }
    
    public void setUserCredentialRoles(Set userCredentialRoles) {
        this.userCredentialRoles = userCredentialRoles;
    }




}


