package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set designations = new HashSet(0);

    public Department() {
    }

    public Department(String name, Set designations) {
       this.name = name;
       this.designations = designations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDesignations() {
        return this.designations;
    }
    
    public void setDesignations(Set designations) {
        this.designations = designations;
    }




}


