package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Designation generated by hbm2java
 */
public class Designation  implements java.io.Serializable {


     private Integer id;
     private Department department;
     private String name;
     private Set workHistoriesForDesignationFrom = new HashSet(0);
     private Set workHistoriesForDesignationTo = new HashSet(0);
     private Set employees = new HashSet(0);

    public Designation() {
    }

	
    public Designation(Department department) {
        this.department = department;
    }
    public Designation(Department department, String name, Set workHistoriesForDesignationFrom, Set workHistoriesForDesignationTo, Set employees) {
       this.department = department;
       this.name = name;
       this.workHistoriesForDesignationFrom = workHistoriesForDesignationFrom;
       this.workHistoriesForDesignationTo = workHistoriesForDesignationTo;
       this.employees = employees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getWorkHistoriesForDesignationFrom() {
        return this.workHistoriesForDesignationFrom;
    }
    
    public void setWorkHistoriesForDesignationFrom(Set workHistoriesForDesignationFrom) {
        this.workHistoriesForDesignationFrom = workHistoriesForDesignationFrom;
    }
    public Set getWorkHistoriesForDesignationTo() {
        return this.workHistoriesForDesignationTo;
    }
    
    public void setWorkHistoriesForDesignationTo(Set workHistoriesForDesignationTo) {
        this.workHistoriesForDesignationTo = workHistoriesForDesignationTo;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


