package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DocumentType generated by hbm2java
 */
public class DocumentType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set employeeDocumentses = new HashSet(0);

    public DocumentType() {
    }

    public DocumentType(String name, Set employeeDocumentses) {
       this.name = name;
       this.employeeDocumentses = employeeDocumentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getEmployeeDocumentses() {
        return this.employeeDocumentses;
    }
    
    public void setEmployeeDocumentses(Set employeeDocumentses) {
        this.employeeDocumentses = employeeDocumentses;
    }




}


