package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1



/**
 * EmployeeDocuments generated by hbm2java
 */
public class EmployeeDocuments  implements java.io.Serializable {


     private Integer id;
     private DocumentType documentType;
     private Employee employee;
     private String url;
     private String name;

    public EmployeeDocuments() {
    }

	
    public EmployeeDocuments(DocumentType documentType, Employee employee) {
        this.documentType = documentType;
        this.employee = employee;
    }
    public EmployeeDocuments(DocumentType documentType, Employee employee, String url, String name) {
       this.documentType = documentType;
       this.employee = employee;
       this.url = url;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DocumentType getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}


