package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer id;
     private Designation designation;
     private GeneralOrganizationProfile generalOrganizationProfile;
     private GeneralUserProfile generalUserProfile;
     private Date registeredDate;
     private String epfNo;
     private Boolean isActive;
     private Date resignationDate;
     private Boolean isEpf;
     private Set claimApprovals = new HashSet(0);
     private Set projectEmployeeses = new HashSet(0);
     private Set universalPayrollManagers = new HashSet(0);
     private Set employeeDocumentses = new HashSet(0);
     private Set claimses = new HashSet(0);
     private Set leaveRequestsForEmployeeIdApprovedBy = new HashSet(0);
     private Set leaveRequestsForEmployeeId = new HashSet(0);
     private Set pettyCashTransactionHistories = new HashSet(0);
     private Set pettyCashWallets = new HashSet(0);
     private Set hrClaimApproves = new HashSet(0);
     private Set workHistories = new HashSet(0);

    public Employee() {
    }

	
    public Employee(Designation designation, GeneralOrganizationProfile generalOrganizationProfile, GeneralUserProfile generalUserProfile, Boolean isActive) {
        this.designation = designation;
        this.generalOrganizationProfile = generalOrganizationProfile;
        this.generalUserProfile = generalUserProfile;
        this.isActive = isActive;
    }
    public Employee(Designation designation, GeneralOrganizationProfile generalOrganizationProfile, GeneralUserProfile generalUserProfile, Date registeredDate, String epfNo, Boolean isActive, Date resignationDate, Boolean isEpf, Set claimApprovals, Set projectEmployeeses, Set universalPayrollManagers, Set employeeDocumentses, Set claimses, Set leaveRequestsForEmployeeIdApprovedBy, Set leaveRequestsForEmployeeId, Set pettyCashTransactionHistories, Set pettyCashWallets, Set hrClaimApproves, Set workHistories) {
       this.designation = designation;
       this.generalOrganizationProfile = generalOrganizationProfile;
       this.generalUserProfile = generalUserProfile;
       this.registeredDate = registeredDate;
       this.epfNo = epfNo;
       this.isActive = isActive;
       this.resignationDate = resignationDate;
       this.isEpf = isEpf;
       this.claimApprovals = claimApprovals;
       this.projectEmployeeses = projectEmployeeses;
       this.universalPayrollManagers = universalPayrollManagers;
       this.employeeDocumentses = employeeDocumentses;
       this.claimses = claimses;
       this.leaveRequestsForEmployeeIdApprovedBy = leaveRequestsForEmployeeIdApprovedBy;
       this.leaveRequestsForEmployeeId = leaveRequestsForEmployeeId;
       this.pettyCashTransactionHistories = pettyCashTransactionHistories;
       this.pettyCashWallets = pettyCashWallets;
       this.hrClaimApproves = hrClaimApproves;
       this.workHistories = workHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Designation getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(Designation designation) {
        this.designation = designation;
    }
    public GeneralOrganizationProfile getGeneralOrganizationProfile() {
        return this.generalOrganizationProfile;
    }
    
    public void setGeneralOrganizationProfile(GeneralOrganizationProfile generalOrganizationProfile) {
        this.generalOrganizationProfile = generalOrganizationProfile;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public Date getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }
    public String getEpfNo() {
        return this.epfNo;
    }
    
    public void setEpfNo(String epfNo) {
        this.epfNo = epfNo;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Date getResignationDate() {
        return this.resignationDate;
    }
    
    public void setResignationDate(Date resignationDate) {
        this.resignationDate = resignationDate;
    }
    public Boolean getIsEpf() {
        return this.isEpf;
    }
    
    public void setIsEpf(Boolean isEpf) {
        this.isEpf = isEpf;
    }
    public Set getClaimApprovals() {
        return this.claimApprovals;
    }
    
    public void setClaimApprovals(Set claimApprovals) {
        this.claimApprovals = claimApprovals;
    }
    public Set getProjectEmployeeses() {
        return this.projectEmployeeses;
    }
    
    public void setProjectEmployeeses(Set projectEmployeeses) {
        this.projectEmployeeses = projectEmployeeses;
    }
    public Set getUniversalPayrollManagers() {
        return this.universalPayrollManagers;
    }
    
    public void setUniversalPayrollManagers(Set universalPayrollManagers) {
        this.universalPayrollManagers = universalPayrollManagers;
    }
    public Set getEmployeeDocumentses() {
        return this.employeeDocumentses;
    }
    
    public void setEmployeeDocumentses(Set employeeDocumentses) {
        this.employeeDocumentses = employeeDocumentses;
    }
    public Set getClaimses() {
        return this.claimses;
    }
    
    public void setClaimses(Set claimses) {
        this.claimses = claimses;
    }
    public Set getLeaveRequestsForEmployeeIdApprovedBy() {
        return this.leaveRequestsForEmployeeIdApprovedBy;
    }
    
    public void setLeaveRequestsForEmployeeIdApprovedBy(Set leaveRequestsForEmployeeIdApprovedBy) {
        this.leaveRequestsForEmployeeIdApprovedBy = leaveRequestsForEmployeeIdApprovedBy;
    }
    public Set getLeaveRequestsForEmployeeId() {
        return this.leaveRequestsForEmployeeId;
    }
    
    public void setLeaveRequestsForEmployeeId(Set leaveRequestsForEmployeeId) {
        this.leaveRequestsForEmployeeId = leaveRequestsForEmployeeId;
    }
    public Set getPettyCashTransactionHistories() {
        return this.pettyCashTransactionHistories;
    }
    
    public void setPettyCashTransactionHistories(Set pettyCashTransactionHistories) {
        this.pettyCashTransactionHistories = pettyCashTransactionHistories;
    }
    public Set getPettyCashWallets() {
        return this.pettyCashWallets;
    }
    
    public void setPettyCashWallets(Set pettyCashWallets) {
        this.pettyCashWallets = pettyCashWallets;
    }
    public Set getHrClaimApproves() {
        return this.hrClaimApproves;
    }
    
    public void setHrClaimApproves(Set hrClaimApproves) {
        this.hrClaimApproves = hrClaimApproves;
    }
    public Set getWorkHistories() {
        return this.workHistories;
    }
    
    public void setWorkHistories(Set workHistories) {
        this.workHistories = workHistories;
    }




}


