package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GeneralUserProfile generated by hbm2java
 */
public class GeneralUserProfile implements java.io.Serializable {

    private Integer id;
    private Country country;
    private Gender gender;
    private String nic;
    private String firstName;
    private String lastName;
    private String address1;
    private String address2;
    private String address3;
    private String mobileNo;
    private String homeNo;
    private String email;
    private Date profileCreatedDate;
    private String faxNo;
    private String contactNo;
    private String nameWithIn;
    private String emergencyContactNo;
    private Date dob;
    private String profileImgUrl;
    private Set userCredentialses = new HashSet(0);
    private Set vouchers = new HashSet(0);
    private Set universalPayrollManagersForGeneralUserProfileGupIdAddedBy = new HashSet(0);
    private Set universalPayrollManagersForGeneralUserProfileGupIdUpdatedBy = new HashSet(0);
    private Set userCredentialHistories = new HashSet(0);
    private Set userCredentialIssuingManagers = new HashSet(0);
    private Set notificationManagers = new HashSet(0);
    private Set userLogins = new HashSet(0);
    private Set gupGopManagers = new HashSet(0);
    private Set attendances = new HashSet(0);
    private Set employees = new HashSet(0);
    private Set helpTickets = new HashSet(0);
    private Set commentsManagers = new HashSet(0);
    private Set helpTicketResponds = new HashSet(0);

    public GeneralUserProfile() {
    }

    public GeneralUserProfile(Country country) {
        this.country = country;
    }

    public GeneralUserProfile(Country country, Gender gender, String nic, String firstName, String lastName, String address1, String address2, String address3, String mobileNo, String homeNo, String email, Date profileCreatedDate, String faxNo, String contactNo, String nameWithIn, String emergencyContactNo, Date dob, String profileImgUrl, Set helpTickets, Set vouchers, Set universalPayrollManagersForGeneralUserProfileGupIdAddedBy, Set universalPayrollManagersForGeneralUserProfileGupIdUpdatedBy, Set notificationManagers, Set commentsManagers, Set userLogins, Set gupGopManagers, Set attendances, Set helpTicketResponds, Set employees, Set userCredentialses, Set userCredentialHistories, Set userCredentialIssuingManagers) {
        this.country = country;
        this.gender = gender;
        this.nic = nic;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address1 = address1;
        this.address2 = address2;
        this.address3 = address3;
        this.mobileNo = mobileNo;
        this.homeNo = homeNo;
        this.email = email;
        this.profileCreatedDate = profileCreatedDate;
        this.faxNo = faxNo;
        this.contactNo = contactNo;
        this.nameWithIn = nameWithIn;
        this.emergencyContactNo = emergencyContactNo;
        this.dob = dob;
        this.profileImgUrl = profileImgUrl;
        this.helpTickets = helpTickets;
        this.vouchers = vouchers;
        this.universalPayrollManagersForGeneralUserProfileGupIdAddedBy = universalPayrollManagersForGeneralUserProfileGupIdAddedBy;
        this.universalPayrollManagersForGeneralUserProfileGupIdUpdatedBy = universalPayrollManagersForGeneralUserProfileGupIdUpdatedBy;
        this.notificationManagers = notificationManagers;
        this.commentsManagers = commentsManagers;
        this.userLogins = userLogins;
        this.gupGopManagers = gupGopManagers;
        this.attendances = attendances;
        this.employees = employees;
        this.userCredentialses = userCredentialses;
        this.userCredentialHistories = userCredentialHistories;
        this.userCredentialIssuingManagers = userCredentialIssuingManagers;
        this.helpTicketResponds = helpTicketResponds;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Country getCountry() {
        return this.country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public Gender getGender() {
        return this.gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public String getNic() {
        return this.nic;
    }

    public void setNic(String nic) {
        this.nic = nic;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getAddress3() {
        return this.address3;
    }

    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    public String getMobileNo() {
        return this.mobileNo;
    }

    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    public String getHomeNo() {
        return this.homeNo;
    }

    public void setHomeNo(String homeNo) {
        this.homeNo = homeNo;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getProfileCreatedDate() {
        return this.profileCreatedDate;
    }

    public void setProfileCreatedDate(Date profileCreatedDate) {
        this.profileCreatedDate = profileCreatedDate;
    }

    public String getFaxNo() {
        return this.faxNo;
    }

    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo;
    }

    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    public String getNameWithIn() {
        return this.nameWithIn;
    }

    public void setNameWithIn(String nameWithIn) {
        this.nameWithIn = nameWithIn;
    }

    public String getEmergencyContactNo() {
        return this.emergencyContactNo;
    }

    public void setEmergencyContactNo(String emergencyContactNo) {
        this.emergencyContactNo = emergencyContactNo;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public String getProfileImgUrl() {
        return this.profileImgUrl;
    }

    public void setProfileImgUrl(String profileImgUrl) {
        this.profileImgUrl = profileImgUrl;
    }

    public Set getHelpTickets() {
        return this.helpTickets;
    }

    public void setHelpTickets(Set helpTickets) {
        this.helpTickets = helpTickets;
    }

    public Set getVouchers() {
        return this.vouchers;
    }

    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }

    public Set getUniversalPayrollManagersForGeneralUserProfileGupIdAddedBy() {
        return this.universalPayrollManagersForGeneralUserProfileGupIdAddedBy;
    }

    public void setUniversalPayrollManagersForGeneralUserProfileGupIdAddedBy(Set universalPayrollManagersForGeneralUserProfileGupIdAddedBy) {
        this.universalPayrollManagersForGeneralUserProfileGupIdAddedBy = universalPayrollManagersForGeneralUserProfileGupIdAddedBy;
    }

    public Set getUniversalPayrollManagersForGeneralUserProfileGupIdUpdatedBy() {
        return this.universalPayrollManagersForGeneralUserProfileGupIdUpdatedBy;
    }

    public void setUniversalPayrollManagersForGeneralUserProfileGupIdUpdatedBy(Set universalPayrollManagersForGeneralUserProfileGupIdUpdatedBy) {
        this.universalPayrollManagersForGeneralUserProfileGupIdUpdatedBy = universalPayrollManagersForGeneralUserProfileGupIdUpdatedBy;
    }

    public Set getNotificationManagers() {
        return this.notificationManagers;
    }

    public void setNotificationManagers(Set notificationManagers) {
        this.notificationManagers = notificationManagers;
    }

    public Set getCommentsManagers() {
        return this.commentsManagers;
    }

    public void setCommentsManagers(Set commentsManagers) {
        this.commentsManagers = commentsManagers;
    }

    public Set getUserLogins() {
        return this.userLogins;
    }

    public void setUserLogins(Set userLogins) {
        this.userLogins = userLogins;
    }

    public Set getGupGopManagers() {
        return this.gupGopManagers;
    }

    public void setGupGopManagers(Set gupGopManagers) {
        this.gupGopManagers = gupGopManagers;
    }

    public Set getAttendances() {
        return this.attendances;
    }

    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }

    public Set getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set employees) {
        this.employees = employees;
    }

    public Set getUserCredentialses() {
        return this.userCredentialses;
    }

    public void setUserCredentialses(Set userCredentialses) {
        this.userCredentialses = userCredentialses;
    }

    public Set getUserCredentialHistories() {
        return this.userCredentialHistories;
    }

    public void setUserCredentialHistories(Set userCredentialHistories) {
        this.userCredentialHistories = userCredentialHistories;
    }

    public Set getUserCredentialIssuingManagers() {
        return this.userCredentialIssuingManagers;
    }

    public void setUserCredentialIssuingManagers(Set userCredentialIssuingManagers) {
        this.userCredentialIssuingManagers = userCredentialIssuingManagers;
    }

    public Set getHelpTicketResponds() {
        return this.helpTicketResponds;
    }

    public void setHelpTicketResponds(Set helpTicketResponds) {
        this.helpTicketResponds = helpTicketResponds;
    }

}
