package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GeneralOrganizationProfile generated by hbm2java
 */
public class GeneralOrganizationProfile  implements java.io.Serializable {


     private Integer id;
     private Country country;
     private OrganizationType organizationType;
     private String name;
     private String address1;
     private String address2;
     private String address3;
     private Date createdDate;
     private String logo;
     private String email;
     private String contactNo;
     private String faxNo;
     private Set gupGopManagers = new HashSet(0);
     private Set employees = new HashSet(0);
     private Set projectses = new HashSet(0);
     private Set projectGopAgreements = new HashSet(0);
     private Set vouchers = new HashSet(0);

    public GeneralOrganizationProfile() {
    }

	
    public GeneralOrganizationProfile(Country country, OrganizationType organizationType, String contactNo) {
        this.country = country;
        this.organizationType = organizationType;
        this.contactNo = contactNo;
    }
    public GeneralOrganizationProfile(Country country, OrganizationType organizationType, String name, String address1, String address2, String address3, Date createdDate, String logo, String email, String contactNo, String faxNo, Set gupGopManagers, Set employees, Set projectses, Set projectGopAgreements, Set vouchers) {
       this.country = country;
       this.organizationType = organizationType;
       this.name = name;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.createdDate = createdDate;
       this.logo = logo;
       this.email = email;
       this.contactNo = contactNo;
       this.faxNo = faxNo;
       this.gupGopManagers = gupGopManagers;
       this.employees = employees;
       this.projectses = projectses;
       this.projectGopAgreements = projectGopAgreements;
       this.vouchers = vouchers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    public OrganizationType getOrganizationType() {
        return this.organizationType;
    }
    
    public void setOrganizationType(OrganizationType organizationType) {
        this.organizationType = organizationType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getFaxNo() {
        return this.faxNo;
    }
    
    public void setFaxNo(String faxNo) {
        this.faxNo = faxNo;
    }
    public Set getGupGopManagers() {
        return this.gupGopManagers;
    }
    
    public void setGupGopManagers(Set gupGopManagers) {
        this.gupGopManagers = gupGopManagers;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }
    public Set getProjectGopAgreements() {
        return this.projectGopAgreements;
    }
    
    public void setProjectGopAgreements(Set projectGopAgreements) {
        this.projectGopAgreements = projectGopAgreements;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }




}


