package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1



/**
 * GupGopManager generated by hbm2java
 */
public class GupGopManager  implements java.io.Serializable {


     private Integer id;
     private GeneralOrganizationProfile generalOrganizationProfile;
     private GeneralUserProfile generalUserProfile;
     private Boolean isActive;

    public GupGopManager() {
    }

	
    public GupGopManager(GeneralOrganizationProfile generalOrganizationProfile, GeneralUserProfile generalUserProfile) {
        this.generalOrganizationProfile = generalOrganizationProfile;
        this.generalUserProfile = generalUserProfile;
    }
    public GupGopManager(GeneralOrganizationProfile generalOrganizationProfile, GeneralUserProfile generalUserProfile, Boolean isActive) {
       this.generalOrganizationProfile = generalOrganizationProfile;
       this.generalUserProfile = generalUserProfile;
       this.isActive = isActive;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralOrganizationProfile getGeneralOrganizationProfile() {
        return this.generalOrganizationProfile;
    }
    
    public void setGeneralOrganizationProfile(GeneralOrganizationProfile generalOrganizationProfile) {
        this.generalOrganizationProfile = generalOrganizationProfile;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


