package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HelpTicketRespond generated by hbm2java
 */
public class HelpTicketRespond  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile respondedGup;
     private HelpTicket helpTicket;
     private HelpTicketRespond helpTicketRespond;
     private HelpTicketRespondType helpTicketRespondType;
     private Date respondDate;
     private String comment;
     private String doc;
     private Double rating;
     private Set helpTicketResponds = new HashSet(0);

    public HelpTicketRespond() {
    }

	
    public HelpTicketRespond(HelpTicket helpTicket, HelpTicketRespondType helpTicketRespondType) {
        this.helpTicket = helpTicket;
        this.helpTicketRespondType = helpTicketRespondType;
    }
    public HelpTicketRespond(GeneralUserProfile respondedGup, HelpTicket helpTicket, HelpTicketRespond helpTicketRespond, HelpTicketRespondType helpTicketRespondType, Date respondDate, String comment, String doc, Double rating, Set helpTicketResponds) {
       this.respondedGup = respondedGup;
       this.helpTicket = helpTicket;
       this.helpTicketRespond = helpTicketRespond;
       this.helpTicketRespondType = helpTicketRespondType;
       this.respondDate = respondDate;
       this.comment = comment;
       this.doc = doc;
       this.rating = rating;
       this.helpTicketResponds = helpTicketResponds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getRespondedGup() {
        return this.respondedGup;
    }
    
    public void setRespondedGup(GeneralUserProfile respondedGup) {
        this.respondedGup = respondedGup;
    }
    public HelpTicket getHelpTicket() {
        return this.helpTicket;
    }
    
    public void setHelpTicket(HelpTicket helpTicket) {
        this.helpTicket = helpTicket;
    }
    public HelpTicketRespond getHelpTicketRespond() {
        return this.helpTicketRespond;
    }
    
    public void setHelpTicketRespond(HelpTicketRespond helpTicketRespond) {
        this.helpTicketRespond = helpTicketRespond;
    }
    public HelpTicketRespondType getHelpTicketRespondType() {
        return this.helpTicketRespondType;
    }
    
    public void setHelpTicketRespondType(HelpTicketRespondType helpTicketRespondType) {
        this.helpTicketRespondType = helpTicketRespondType;
    }
    public Date getRespondDate() {
        return this.respondDate;
    }
    
    public void setRespondDate(Date respondDate) {
        this.respondDate = respondDate;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public String getDoc() {
        return this.doc;
    }
    
    public void setDoc(String doc) {
        this.doc = doc;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public Set getHelpTicketResponds() {
        return this.helpTicketResponds;
    }
    
    public void setHelpTicketResponds(Set helpTicketResponds) {
        this.helpTicketResponds = helpTicketResponds;
    }




}


