package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HelpTicketCategory generated by hbm2java
 */
public class HelpTicketCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set helpTickets = new HashSet(0);

    public HelpTicketCategory() {
    }

    public HelpTicketCategory(String name, Set helpTickets) {
       this.name = name;
       this.helpTickets = helpTickets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getHelpTickets() {
        return this.helpTickets;
    }
    
    public void setHelpTickets(Set helpTickets) {
        this.helpTickets = helpTickets;
    }




}


