package Model.Mapping;
// Generated Jan 3, 2024 1:11:36 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HelpTicket generated by hbm2java
 */
public class HelpTicket  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile requestedBy;
     private HelpTicketCategory helpTicketCategory;
     private HelpTicketStatus helpTicketStatus;
     private HelpTicketSubmitType helpTicketSubmitType;
     private Projects projects;
     private UserLogin submitRefference;
     private String ticketId;
     private Date enteredDate;
     private String description;
     private Double rating;
     private Set helpTicketAttachmentses = new HashSet(0);
     private Set helpTicketResponds = new HashSet(0);

    public HelpTicket() {
    }

	
    public HelpTicket(HelpTicketCategory helpTicketCategory, HelpTicketStatus helpTicketStatus, HelpTicketSubmitType helpTicketSubmitType) {
        this.helpTicketCategory = helpTicketCategory;
        this.helpTicketStatus = helpTicketStatus;
        this.helpTicketSubmitType = helpTicketSubmitType;
    }
    public HelpTicket(GeneralUserProfile requestedBy, HelpTicketCategory helpTicketCategory, HelpTicketStatus helpTicketStatus, HelpTicketSubmitType helpTicketSubmitType, Projects projects, UserLogin submitRefference, String ticketId, Date enteredDate, String description, Double rating, Set helpTicketAttachmentses, Set helpTicketResponds) {
       this.requestedBy = requestedBy;
       this.helpTicketCategory = helpTicketCategory;
       this.helpTicketStatus = helpTicketStatus;
       this.helpTicketSubmitType = helpTicketSubmitType;
       this.projects = projects;
       this.submitRefference = submitRefference;
       this.ticketId = ticketId;
       this.enteredDate = enteredDate;
       this.description = description;
       this.rating = rating;
       this.helpTicketAttachmentses = helpTicketAttachmentses;
       this.helpTicketResponds = helpTicketResponds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getRequestedBy() {
        return this.requestedBy;
    }
    
    public void setRequestedBy(GeneralUserProfile requestedBy) {
        this.requestedBy = requestedBy;
    }
    public HelpTicketCategory getHelpTicketCategory() {
        return this.helpTicketCategory;
    }
    
    public void setHelpTicketCategory(HelpTicketCategory helpTicketCategory) {
        this.helpTicketCategory = helpTicketCategory;
    }
    public HelpTicketStatus getHelpTicketStatus() {
        return this.helpTicketStatus;
    }
    
    public void setHelpTicketStatus(HelpTicketStatus helpTicketStatus) {
        this.helpTicketStatus = helpTicketStatus;
    }
    public HelpTicketSubmitType getHelpTicketSubmitType() {
        return this.helpTicketSubmitType;
    }
    
    public void setHelpTicketSubmitType(HelpTicketSubmitType helpTicketSubmitType) {
        this.helpTicketSubmitType = helpTicketSubmitType;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public UserLogin getSubmitRefference() {
        return this.submitRefference;
    }
    
    public void setSubmitRefference(UserLogin submitRefference) {
        this.submitRefference = submitRefference;
    }
    public String getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public Set getHelpTicketAttachmentses() {
        return this.helpTicketAttachmentses;
    }
    
    public void setHelpTicketAttachmentses(Set helpTicketAttachmentses) {
        this.helpTicketAttachmentses = helpTicketAttachmentses;
    }
    public Set getHelpTicketResponds() {
        return this.helpTicketResponds;
    }
    
    public void setHelpTicketResponds(Set helpTicketResponds) {
        this.helpTicketResponds = helpTicketResponds;
    }




}


