package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HelpTicketRespondType generated by hbm2java
 */
public class HelpTicketRespondType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set helpTicketResponds = new HashSet(0);

    public HelpTicketRespondType() {
    }

    public HelpTicketRespondType(String name, Set helpTicketResponds) {
       this.name = name;
       this.helpTicketResponds = helpTicketResponds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getHelpTicketResponds() {
        return this.helpTicketResponds;
    }
    
    public void setHelpTicketResponds(Set helpTicketResponds) {
        this.helpTicketResponds = helpTicketResponds;
    }




}


