package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * HelpTicketSubmitType generated by hbm2java
 */
public class HelpTicketSubmitType  implements java.io.Serializable {


     private int id;
     private String name;
     private Set helpTickets = new HashSet(0);

    public HelpTicketSubmitType() {
    }

	
    public HelpTicketSubmitType(int id) {
        this.id = id;
    }
    public HelpTicketSubmitType(int id, String name, Set helpTickets) {
       this.id = id;
       this.name = name;
       this.helpTickets = helpTickets;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getHelpTickets() {
        return this.helpTickets;
    }
    
    public void setHelpTickets(Set helpTickets) {
        this.helpTickets = helpTickets;
    }




}


