package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1



/**
 * HelpTicketAttachments generated by hbm2java
 */
public class HelpTicketAttachments  implements java.io.Serializable {


     private Integer id;
     private HelpTicket helpTicket;
     private String url;

    public HelpTicketAttachments() {
    }

	
    public HelpTicketAttachments(HelpTicket helpTicket) {
        this.helpTicket = helpTicket;
    }
    public HelpTicketAttachments(HelpTicket helpTicket, String url) {
       this.helpTicket = helpTicket;
       this.url = url;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public HelpTicket getHelpTicket() {
        return this.helpTicket;
    }
    
    public void setHelpTicket(HelpTicket helpTicket) {
        this.helpTicket = helpTicket;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


