package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HrClaimApprove generated by hbm2java
 */
public class HrClaimApprove  implements java.io.Serializable {


     private Integer id;
     private Claims claims;
     private Employee employee;
     private Status status;
     private Date approvedDate;
     private String dissaproveReason;

    public HrClaimApprove() {
    }

    public HrClaimApprove(Claims claims, Employee employee, Status status, Date approvedDate, String dissaproveReason) {
       this.claims = claims;
       this.employee = employee;
       this.status = status;
       this.approvedDate = approvedDate;
       this.dissaproveReason = dissaproveReason;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Claims getClaims() {
        return this.claims;
    }
    
    public void setClaims(Claims claims) {
        this.claims = claims;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }
    public String getDissaproveReason() {
        return this.dissaproveReason;
    }
    
    public void setDissaproveReason(String dissaproveReason) {
        this.dissaproveReason = dissaproveReason;
    }




}


