package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InterfaceMenu generated by hbm2java
 */
public class InterfaceMenu  implements java.io.Serializable {


     private Integer ifId;
     private String menuName;
     private String icon;
     private Integer priority;
     private Set systemInterfaces = new HashSet(0);

    public InterfaceMenu() {
    }

    public InterfaceMenu(String menuName, String icon, Integer priority, Set systemInterfaces) {
       this.menuName = menuName;
       this.icon = icon;
       this.priority = priority;
       this.systemInterfaces = systemInterfaces;
    }
   
    public Integer getIfId() {
        return this.ifId;
    }
    
    public void setIfId(Integer ifId) {
        this.ifId = ifId;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    public Set getSystemInterfaces() {
        return this.systemInterfaces;
    }
    
    public void setSystemInterfaces(Set systemInterfaces) {
        this.systemInterfaces = systemInterfaces;
    }




}


