package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * InterfaceSubMenu generated by hbm2java
 */
public class InterfaceSubMenu  implements java.io.Serializable {


     private Integer ifsId;
     private String name;
     private Set systemInterfaces = new HashSet(0);

    public InterfaceSubMenu() {
    }

    public InterfaceSubMenu(String name, Set systemInterfaces) {
       this.name = name;
       this.systemInterfaces = systemInterfaces;
    }
   
    public Integer getIfsId() {
        return this.ifsId;
    }
    
    public void setIfsId(Integer ifsId) {
        this.ifsId = ifsId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getSystemInterfaces() {
        return this.systemInterfaces;
    }
    
    public void setSystemInterfaces(Set systemInterfaces) {
        this.systemInterfaces = systemInterfaces;
    }




}


