package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LeaveApprovalStatus generated by hbm2java
 */
public class LeaveApprovalStatus  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set leaveRequests = new HashSet(0);

    public LeaveApprovalStatus() {
    }

    public LeaveApprovalStatus(String name, Set leaveRequests) {
       this.name = name;
       this.leaveRequests = leaveRequests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getLeaveRequests() {
        return this.leaveRequests;
    }
    
    public void setLeaveRequests(Set leaveRequests) {
        this.leaveRequests = leaveRequests;
    }




}


