package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * LeaveRequest generated by hbm2java
 */
public class LeaveRequest implements java.io.Serializable {

    private Integer id;
    private Employee employeeByEmployeeIdApprovedBy;
    private Employee employeeByEmployeeId;
    private LeaveApprovalStatus leaveApprovalStatus;
    private LeaveType leaveType;
    private Date requestedDate;
    private String reason;
    private String comment;
    private Date dateFrom;
    private Date dateTo;
    private Date approvedDate;
    private String rejectReason;

    public LeaveRequest() {
    }

    public LeaveRequest(Employee employeeByEmployeeId, LeaveApprovalStatus leaveApprovalStatus, LeaveType leaveType) {
        this.employeeByEmployeeId = employeeByEmployeeId;
        this.leaveApprovalStatus = leaveApprovalStatus;
        this.leaveType = leaveType;
    }

    public LeaveRequest(Employee employeeByEmployeeIdApprovedBy, Employee employeeByEmployeeId, LeaveApprovalStatus leaveApprovalStatus, LeaveType leaveType, Date requestedDate, String reason, String comment, Date dateFrom, Date dateTo, Date approvedDate, String rejectReason) {
        this.employeeByEmployeeIdApprovedBy = employeeByEmployeeIdApprovedBy;
        this.employeeByEmployeeId = employeeByEmployeeId;
        this.leaveApprovalStatus = leaveApprovalStatus;
        this.leaveType = leaveType;
        this.requestedDate = requestedDate;
        this.reason = reason;
        this.comment = comment;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.approvedDate = approvedDate;
        this.rejectReason = rejectReason;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Employee getEmployeeByEmployeeIdApprovedBy() {
        return this.employeeByEmployeeIdApprovedBy;
    }

    public void setEmployeeByEmployeeIdApprovedBy(Employee employeeByEmployeeIdApprovedBy) {
        this.employeeByEmployeeIdApprovedBy = employeeByEmployeeIdApprovedBy;
    }

    public Employee getEmployeeByEmployeeId() {
        return this.employeeByEmployeeId;
    }

    public void setEmployeeByEmployeeId(Employee employeeByEmployeeId) {
        this.employeeByEmployeeId = employeeByEmployeeId;
    }

    public LeaveApprovalStatus getLeaveApprovalStatus() {
        return this.leaveApprovalStatus;
    }

    public void setLeaveApprovalStatus(LeaveApprovalStatus leaveApprovalStatus) {
        this.leaveApprovalStatus = leaveApprovalStatus;
    }

    public LeaveType getLeaveType() {
        return this.leaveType;
    }

    public void setLeaveType(LeaveType leaveType) {
        this.leaveType = leaveType;
    }

    public Date getRequestedDate() {
        return this.requestedDate;
    }

    public void setRequestedDate(Date requestedDate) {
        this.requestedDate = requestedDate;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Date getDateFrom() {
        return this.dateFrom;
    }

    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public Date getDateTo() {
        return this.dateTo;
    }

    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    public Date getApprovedDate() {
        return this.approvedDate;
    }

    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    public String getRejectReason() {
        return rejectReason;
    }

    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

}
