package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LoginSession generated by hbm2java
 */
public class LoginSession  implements java.io.Serializable {


     private Integer id;
     private UserLogin userLogin;
     private Date startTime;
     private Date endTime;
     private String ip;
     private Set vouchers = new HashSet(0);

    public LoginSession() {
    }

	
    public LoginSession(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public LoginSession(UserLogin userLogin, Date startTime, Date endTime, String ip, Set vouchers) {
       this.userLogin = userLogin;
       this.startTime = startTime;
       this.endTime = endTime;
       this.ip = ip;
       this.vouchers = vouchers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }




}


