package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NotificationManager generated by hbm2java
 */
public class NotificationManager  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile generalUserProfile;
     private NotificationType notificationType;
     private Date notifyDate;
     private String description;
     private Boolean isViewed;
     private Date viewedDate;
     private int reference;

    public NotificationManager() {
    }

    public NotificationManager(GeneralUserProfile generalUserProfile, NotificationType notificationType, Date notifyDate, String description, Boolean isViewed, Date viewedDate, int reference) {
       this.generalUserProfile = generalUserProfile;
       this.notificationType = notificationType;
       this.notifyDate = notifyDate;
       this.description = description;
       this.isViewed = isViewed;
       this.viewedDate = viewedDate;
       this.reference = reference;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public NotificationType getNotificationType() {
        return this.notificationType;
    }
    
    public void setNotificationType(NotificationType notificationType) {
        this.notificationType = notificationType;
    }
    public Date getNotifyDate() {
        return this.notifyDate;
    }
    
    public void setNotifyDate(Date notifyDate) {
        this.notifyDate = notifyDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Boolean getIsViewed() {
        return this.isViewed;
    }
    
    public void setIsViewed(Boolean isViewed) {
        this.isViewed = isViewed;
    }
    public Date getViewedDate() {
        return this.viewedDate;
    }
    
    public void setViewedDate(Date viewedDate) {
        this.viewedDate = viewedDate;
    }
    public int getReference() {
        return this.reference;
    }
    
    public void setReference(int reference) {
        this.reference = reference;
    }




}


