package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NotificationType generated by hbm2java
 */
public class NotificationType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set notificationManagers = new HashSet(0);

    public NotificationType() {
    }

	
    public NotificationType(String name) {
        this.name = name;
    }
    public NotificationType(String name, Set notificationManagers) {
       this.name = name;
       this.notificationManagers = notificationManagers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getNotificationManagers() {
        return this.notificationManagers;
    }
    
    public void setNotificationManagers(Set notificationManagers) {
        this.notificationManagers = notificationManagers;
    }




}


