package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaymentMode generated by hbm2java
 */
public class PaymentMode  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set vouchers = new HashSet(0);

    public PaymentMode() {
    }

    public PaymentMode(String name, Set vouchers) {
       this.name = name;
       this.vouchers = vouchers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }




}


