package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PettyCashWallet generated by hbm2java
 */
public class PettyCashWallet  implements java.io.Serializable {


     private Integer id;
     private Employee employee;
     private Double amount;
     private Date updatedDate;
     private Set pettyCashTransactionHistories = new HashSet(0);

    public PettyCashWallet() {
    }

	
    public PettyCashWallet(Employee employee) {
        this.employee = employee;
    }
    public PettyCashWallet(Employee employee, Double amount, Date updatedDate, Set pettyCashTransactionHistories) {
       this.employee = employee;
       this.amount = amount;
       this.updatedDate = updatedDate;
       this.pettyCashTransactionHistories = pettyCashTransactionHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public Set getPettyCashTransactionHistories() {
        return this.pettyCashTransactionHistories;
    }
    
    public void setPettyCashTransactionHistories(Set pettyCashTransactionHistories) {
        this.pettyCashTransactionHistories = pettyCashTransactionHistories;
    }




}


