package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PettyCashTransactionHistoryDocument generated by hbm2java
 */
public class PettyCashTransactionHistoryDocument  implements java.io.Serializable {


     private Integer id;
     private PettyCashTransactionHistory pettyCashTransactionHistory;
     private Double amount;
     private Date transactionDate;
     private String doc;
     private Date uploadedDate;
     private String expenseDescription;

    public PettyCashTransactionHistoryDocument() {
    }

	
    public PettyCashTransactionHistoryDocument(PettyCashTransactionHistory pettyCashTransactionHistory) {
        this.pettyCashTransactionHistory = pettyCashTransactionHistory;
    }
    public PettyCashTransactionHistoryDocument(PettyCashTransactionHistory pettyCashTransactionHistory, Double amount, Date transactionDate, String doc, Date uploadedDate, String expenseDescription) {
       this.pettyCashTransactionHistory = pettyCashTransactionHistory;
       this.amount = amount;
       this.transactionDate = transactionDate;
       this.doc = doc;
       this.uploadedDate = uploadedDate;
       this.expenseDescription = expenseDescription;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PettyCashTransactionHistory getPettyCashTransactionHistory() {
        return this.pettyCashTransactionHistory;
    }
    
    public void setPettyCashTransactionHistory(PettyCashTransactionHistory pettyCashTransactionHistory) {
        this.pettyCashTransactionHistory = pettyCashTransactionHistory;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public String getDoc() {
        return this.doc;
    }
    
    public void setDoc(String doc) {
        this.doc = doc;
    }
    public Date getUploadedDate() {
        return this.uploadedDate;
    }
    
    public void setUploadedDate(Date uploadedDate) {
        this.uploadedDate = uploadedDate;
    }
    public String getExpenseDescription() {
        return this.expenseDescription;
    }
    
    public void setExpenseDescription(String expenseDescription) {
        this.expenseDescription = expenseDescription;
    }




}


