package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PettyCashApprovalLevel generated by hbm2java
 */
public class PettyCashApprovalLevel  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set pettyCashTransactionHistories = new HashSet(0);

    public PettyCashApprovalLevel() {
    }

    public PettyCashApprovalLevel(String name, Set pettyCashTransactionHistories) {
       this.name = name;
       this.pettyCashTransactionHistories = pettyCashTransactionHistories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPettyCashTransactionHistories() {
        return this.pettyCashTransactionHistories;
    }
    
    public void setPettyCashTransactionHistories(Set pettyCashTransactionHistories) {
        this.pettyCashTransactionHistories = pettyCashTransactionHistories;
    }




}


