package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PettyCashTransactionHistory generated by hbm2java
 */
public class PettyCashTransactionHistory  implements java.io.Serializable {


     private Integer id;
     private Employee employee;
     private PettyCashApprovalLevel pettyCashApprovalLevel;
     private PettyCashWallet pettyCashWallet;
     private TransactionType transactionType;
     private Double amount;
     private Date transactionDate;
     private Date approvalDate;
     private String description;
     private String comment;
     private Set pettyCashTransactionHistoryDocuments = new HashSet(0);

    public PettyCashTransactionHistory() {
    }

	
    public PettyCashTransactionHistory(PettyCashApprovalLevel pettyCashApprovalLevel, PettyCashWallet pettyCashWallet, TransactionType transactionType) {
        this.pettyCashApprovalLevel = pettyCashApprovalLevel;
        this.pettyCashWallet = pettyCashWallet;
        this.transactionType = transactionType;
    }
    public PettyCashTransactionHistory(Employee employee, PettyCashApprovalLevel pettyCashApprovalLevel, PettyCashWallet pettyCashWallet, TransactionType transactionType, Double amount, Date transactionDate, Date approvalDate, String description, String comment, Set pettyCashTransactionHistoryDocuments) {
       this.employee = employee;
       this.pettyCashApprovalLevel = pettyCashApprovalLevel;
       this.pettyCashWallet = pettyCashWallet;
       this.transactionType = transactionType;
       this.amount = amount;
       this.transactionDate = transactionDate;
       this.approvalDate = approvalDate;
       this.description = description;
       this.comment = comment;
       this.pettyCashTransactionHistoryDocuments = pettyCashTransactionHistoryDocuments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public PettyCashApprovalLevel getPettyCashApprovalLevel() {
        return this.pettyCashApprovalLevel;
    }
    
    public void setPettyCashApprovalLevel(PettyCashApprovalLevel pettyCashApprovalLevel) {
        this.pettyCashApprovalLevel = pettyCashApprovalLevel;
    }
    public PettyCashWallet getPettyCashWallet() {
        return this.pettyCashWallet;
    }
    
    public void setPettyCashWallet(PettyCashWallet pettyCashWallet) {
        this.pettyCashWallet = pettyCashWallet;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public Date getApprovalDate() {
        return this.approvalDate;
    }
    
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Set getPettyCashTransactionHistoryDocuments() {
        return this.pettyCashTransactionHistoryDocuments;
    }
    
    public void setPettyCashTransactionHistoryDocuments(Set pettyCashTransactionHistoryDocuments) {
        this.pettyCashTransactionHistoryDocuments = pettyCashTransactionHistoryDocuments;
    }




}


