package Model.Mapping;
// Generated May 21, 2024 7:35:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProjectTasks generated by hbm2java
 */
public class ProjectTasks  implements java.io.Serializable {


     private Integer id;
     private ProjectTaskPriority projectTaskPriority;
     private Projects projects;
     private Status status;
     private String name;
     private String note;
     private Date assignedDate;
     private Date dueDate;
     private Date startDate;
     private Date completedDate;
     private Date endDate;
     private Boolean isActive;
     private Set taskAssignEmployeeses = new HashSet(0);
     private Set commentsManagers = new HashSet(0);
     private Set projectTaskAttachmentses = new HashSet(0);

    public ProjectTasks() {
    }

	
    public ProjectTasks(ProjectTaskPriority projectTaskPriority, Projects projects, Status status) {
        this.projectTaskPriority = projectTaskPriority;
        this.projects = projects;
        this.status = status;
    }
    public ProjectTasks(ProjectTaskPriority projectTaskPriority, Projects projects, Status status, String name, String note, Date assignedDate, Date dueDate, Date startDate, Date completedDate, Date endDate, Boolean isActive, Set taskAssignEmployeeses, Set commentsManagers, Set projectTaskAttachmentses) {
       this.projectTaskPriority = projectTaskPriority;
       this.projects = projects;
       this.status = status;
       this.name = name;
       this.note = note;
       this.assignedDate = assignedDate;
       this.dueDate = dueDate;
       this.startDate = startDate;
       this.completedDate = completedDate;
       this.endDate = endDate;
       this.isActive = isActive;
       this.taskAssignEmployeeses = taskAssignEmployeeses;
       this.commentsManagers = commentsManagers;
       this.projectTaskAttachmentses = projectTaskAttachmentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ProjectTaskPriority getProjectTaskPriority() {
        return this.projectTaskPriority;
    }
    
    public void setProjectTaskPriority(ProjectTaskPriority projectTaskPriority) {
        this.projectTaskPriority = projectTaskPriority;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Date getAssignedDate() {
        return this.assignedDate;
    }
    
    public void setAssignedDate(Date assignedDate) {
        this.assignedDate = assignedDate;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getCompletedDate() {
        return this.completedDate;
    }
    
    public void setCompletedDate(Date completedDate) {
        this.completedDate = completedDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Set getTaskAssignEmployeeses() {
        return this.taskAssignEmployeeses;
    }
    
    public void setTaskAssignEmployeeses(Set taskAssignEmployeeses) {
        this.taskAssignEmployeeses = taskAssignEmployeeses;
    }
    public Set getCommentsManagers() {
        return this.commentsManagers;
    }
    
    public void setCommentsManagers(Set commentsManagers) {
        this.commentsManagers = commentsManagers;
    }
    public Set getProjectTaskAttachmentses() {
        return this.projectTaskAttachmentses;
    }
    
    public void setProjectTaskAttachmentses(Set projectTaskAttachmentses) {
        this.projectTaskAttachmentses = projectTaskAttachmentses;
    }




}


