package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * ProjectTaskPriority generated by hbm2java
 */
public class ProjectTaskPriority  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set projectTaskses = new HashSet(0);

    public ProjectTaskPriority() {
    }

    public ProjectTaskPriority(String name, Set projectTaskses) {
       this.name = name;
        this.projectTaskses = projectTaskses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProjectTaskses() {
        return this.projectTaskses;
    }
    
    public void setProjectTaskses(Set projectTaskses) {
        this.projectTaskses = projectTaskses;
    }



}


