package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1



/**
 * ProjectTaskAttachments generated by hbm2java
 */
public class ProjectTaskAttachments  implements java.io.Serializable {


     private Integer id;
     private ProjectTasks projectTasks;
     private String url;

    public ProjectTaskAttachments() {
    }

    public ProjectTaskAttachments(ProjectTasks projectTasks, String url) {
       this.projectTasks = projectTasks;
       this.url = url;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ProjectTasks getProjectTasks() {
        return this.projectTasks;
    }
    
    public void setProjectTasks(ProjectTasks projectTasks) {
        this.projectTasks = projectTasks;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


