package Model.Mapping;
// Generated May 21, 2024 8:03:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProjectEmployees generated by hbm2java
 */
public class ProjectEmployees  implements java.io.Serializable {


     private Integer id;
     private Employee employee;
     private ProjectEmployeeRole projectEmployeeRole;
     private Projects projects;
     private Date assignedDate;
     private Boolean isActive;
     private Set taskAssignEmployeeses = new HashSet(0);
     private Set commentsManagers = new HashSet(0);

    public ProjectEmployees() {
    }

	
    public ProjectEmployees(Employee employee, ProjectEmployeeRole projectEmployeeRole, Projects projects, Date assignedDate) {
        this.employee = employee;
        this.projectEmployeeRole = projectEmployeeRole;
        this.projects = projects;
        this.assignedDate = assignedDate;
    }
    public ProjectEmployees(Employee employee, ProjectEmployeeRole projectEmployeeRole, Projects projects, Date assignedDate, Boolean isActive, Set taskAssignEmployeeses, Set commentsManagers) {
       this.employee = employee;
       this.projectEmployeeRole = projectEmployeeRole;
       this.projects = projects;
       this.assignedDate = assignedDate;
       this.isActive = isActive;
       this.taskAssignEmployeeses = taskAssignEmployeeses;
       this.commentsManagers = commentsManagers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public ProjectEmployeeRole getProjectEmployeeRole() {
        return this.projectEmployeeRole;
    }
    
    public void setProjectEmployeeRole(ProjectEmployeeRole projectEmployeeRole) {
        this.projectEmployeeRole = projectEmployeeRole;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public Date getAssignedDate() {
        return this.assignedDate;
    }
    
    public void setAssignedDate(Date assignedDate) {
        this.assignedDate = assignedDate;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Set getTaskAssignEmployeeses() {
        return this.taskAssignEmployeeses;
    }
    
    public void setTaskAssignEmployeeses(Set taskAssignEmployeeses) {
        this.taskAssignEmployeeses = taskAssignEmployeeses;
    }
    public Set getCommentsManagers() {
        return this.commentsManagers;
    }
    
    public void setCommentsManagers(Set commentsManagers) {
        this.commentsManagers = commentsManagers;
    }




}


