package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProjectGopAgreement generated by hbm2java
 */
public class ProjectGopAgreement  implements java.io.Serializable {


     private Integer id;
     private GeneralOrganizationProfile generalOrganizationProfile;
     private Projects projects;
     private String document;
     private Date uploadedDate;

    public ProjectGopAgreement() {
    }

	
    public ProjectGopAgreement(GeneralOrganizationProfile generalOrganizationProfile, Projects projects) {
        this.generalOrganizationProfile = generalOrganizationProfile;
        this.projects = projects;
    }
    public ProjectGopAgreement(GeneralOrganizationProfile generalOrganizationProfile, Projects projects, String document, Date uploadedDate) {
       this.generalOrganizationProfile = generalOrganizationProfile;
       this.projects = projects;
       this.document = document;
       this.uploadedDate = uploadedDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralOrganizationProfile getGeneralOrganizationProfile() {
        return this.generalOrganizationProfile;
    }
    
    public void setGeneralOrganizationProfile(GeneralOrganizationProfile generalOrganizationProfile) {
        this.generalOrganizationProfile = generalOrganizationProfile;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }
    public Date getUploadedDate() {
        return this.uploadedDate;
    }
    
    public void setUploadedDate(Date uploadedDate) {
        this.uploadedDate = uploadedDate;
    }




}


