package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projects generated by hbm2java
 */
public class Projects  implements java.io.Serializable {


     private Integer id;
     private GeneralOrganizationProfile generalOrganizationProfile;
     private Status status;
     private String name;
     private String description;
     private Date startedDate;
     private Date completedDate;
     private String logoUrl;
     private String projectsDocument;
     private Boolean isActive;
     private Set projectEmployeeses = new HashSet(0);
     private Set commentsManagers = new HashSet(0);
     private Set projectTaskses = new HashSet(0);
     private Set userCredentialses = new HashSet(0);
     private Set projectGopAgreements = new HashSet(0);
     private Set helpTickets = new HashSet(0);

    public Projects() {
    }

	
    public Projects(Date startedDate) {
        this.startedDate = startedDate;
    }
    public Projects(GeneralOrganizationProfile generalOrganizationProfile, Status status, String name, String description, Date startedDate, Date completedDate, String logoUrl, String projectsDocument, Boolean isActive, Set projectEmployeeses, Set commentsManagers, Set projectTaskses, Set userCredentialses, Set projectGopAgreements, Set helpTickets) {
       this.generalOrganizationProfile = generalOrganizationProfile;
       this.status = status;
       this.name = name;
       this.description = description;
       this.startedDate = startedDate;
       this.completedDate = completedDate;
       this.logoUrl = logoUrl;
       this.projectsDocument = projectsDocument;
       this.isActive = isActive;
       this.projectEmployeeses = projectEmployeeses;
       this.commentsManagers = commentsManagers;
       this.projectTaskses = projectTaskses;
       this.userCredentialses = userCredentialses;
       this.projectGopAgreements = projectGopAgreements;
       this.helpTickets = helpTickets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralOrganizationProfile getGeneralOrganizationProfile() {
        return this.generalOrganizationProfile;
    }
    
    public void setGeneralOrganizationProfile(GeneralOrganizationProfile generalOrganizationProfile) {
        this.generalOrganizationProfile = generalOrganizationProfile;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getStartedDate() {
        return this.startedDate;
    }
    
    public void setStartedDate(Date startedDate) {
        this.startedDate = startedDate;
    }
    public Date getCompletedDate() {
        return this.completedDate;
    }
    
    public void setCompletedDate(Date completedDate) {
        this.completedDate = completedDate;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public String getProjectsDocument() {
        return this.projectsDocument;
    }
    
    public void setProjectsDocument(String projectsDocument) {
        this.projectsDocument = projectsDocument;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Set getProjectEmployeeses() {
        return this.projectEmployeeses;
    }
    
    public void setProjectEmployeeses(Set projectEmployeeses) {
        this.projectEmployeeses = projectEmployeeses;
    }
    public Set getCommentsManagers() {
        return this.commentsManagers;
    }
    
    public void setCommentsManagers(Set commentsManagers) {
        this.commentsManagers = commentsManagers;
    }
    public Set getProjectTaskses() {
        return this.projectTaskses;
    }
    
    public void setProjectTaskses(Set projectTaskses) {
        this.projectTaskses = projectTaskses;
    }
    public Set getUserCredentialses() {
        return this.userCredentialses;
    }
    
    public void setUserCredentialses(Set userCredentialses) {
        this.userCredentialses = userCredentialses;
    }
    public Set getProjectGopAgreements() {
        return this.projectGopAgreements;
    }
    
    public void setProjectGopAgreements(Set projectGopAgreements) {
        this.projectGopAgreements = projectGopAgreements;
    }
    public Set getHelpTickets() {
        return this.helpTickets;
    }
    
    public void setHelpTickets(Set helpTickets) {
        this.helpTickets = helpTickets;
    }




}


