package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProjectEmployeeRole generated by hbm2java
 */
public class ProjectEmployeeRole  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set projectEmployeeses = new HashSet(0);

    public ProjectEmployeeRole() {
    }

	
    public ProjectEmployeeRole(String name) {
        this.name = name;
    }
    public ProjectEmployeeRole(String name, Set projectEmployeeses) {
       this.name = name;
       this.projectEmployeeses = projectEmployeeses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProjectEmployeeses() {
        return this.projectEmployeeses;
    }
    
    public void setProjectEmployeeses(Set projectEmployeeses) {
        this.projectEmployeeses = projectEmployeeses;
    }




}


