package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set projectTaskses = new HashSet(0);
     private Set projectses = new HashSet(0);
     private Set hrClaimApproves = new HashSet(0);

    public Status() {
    }

	
    public Status(String name) {
        this.name = name;
    }
    public Status(String name, Set projectTaskses, Set projectses, Set hrClaimApproves) {
       this.name = name;
       this.projectTaskses = projectTaskses;
       this.projectses = projectses;
       this.hrClaimApproves = hrClaimApproves;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProjectTaskses() {
        return this.projectTaskses;
    }
    
    public void setProjectTaskses(Set projectTaskses) {
        this.projectTaskses = projectTaskses;
    }
    public Set getProjectses() {
        return this.projectses;
    }
    
    public void setProjectses(Set projectses) {
        this.projectses = projectses;
    }
    public Set getHrClaimApproves() {
        return this.hrClaimApproves;
    }
    
    public void setHrClaimApproves(Set hrClaimApproves) {
        this.hrClaimApproves = hrClaimApproves;
    }




}


