package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SystemInterface generated by hbm2java
 */
public class SystemInterface  implements java.io.Serializable {


     private Integer siId;
     private InterfaceMenu interfaceMenu;
     private InterfaceSubMenu interfaceSubMenu;
     private String interfaceName;
     private String displayName;
     private String url;
     private String icon;
     private Set userRoleHasSystemInterfaces = new HashSet(0);
     private Set userLoginHasSystemInterfaces = new HashSet(0);

    public SystemInterface() {
    }

    public SystemInterface(InterfaceMenu interfaceMenu, InterfaceSubMenu interfaceSubMenu, String interfaceName, String displayName, String url, String icon, Set userRoleHasSystemInterfaces, Set userLoginHasSystemInterfaces) {
       this.interfaceMenu = interfaceMenu;
       this.interfaceSubMenu = interfaceSubMenu;
       this.interfaceName = interfaceName;
       this.displayName = displayName;
       this.url = url;
       this.icon = icon;
       this.userRoleHasSystemInterfaces = userRoleHasSystemInterfaces;
       this.userLoginHasSystemInterfaces = userLoginHasSystemInterfaces;
    }
   
    public Integer getSiId() {
        return this.siId;
    }
    
    public void setSiId(Integer siId) {
        this.siId = siId;
    }
    public InterfaceMenu getInterfaceMenu() {
        return this.interfaceMenu;
    }
    
    public void setInterfaceMenu(InterfaceMenu interfaceMenu) {
        this.interfaceMenu = interfaceMenu;
    }
    public InterfaceSubMenu getInterfaceSubMenu() {
        return this.interfaceSubMenu;
    }
    
    public void setInterfaceSubMenu(InterfaceSubMenu interfaceSubMenu) {
        this.interfaceSubMenu = interfaceSubMenu;
    }
    public String getInterfaceName() {
        return this.interfaceName;
    }
    
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
    public Set getUserRoleHasSystemInterfaces() {
        return this.userRoleHasSystemInterfaces;
    }
    
    public void setUserRoleHasSystemInterfaces(Set userRoleHasSystemInterfaces) {
        this.userRoleHasSystemInterfaces = userRoleHasSystemInterfaces;
    }
    public Set getUserLoginHasSystemInterfaces() {
        return this.userLoginHasSystemInterfaces;
    }
    
    public void setUserLoginHasSystemInterfaces(Set userLoginHasSystemInterfaces) {
        this.userLoginHasSystemInterfaces = userLoginHasSystemInterfaces;
    }




}


