package Model.Mapping;
// Generated May 21, 2024 7:35:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TaskAssignEmployees generated by hbm2java
 */
public class TaskAssignEmployees  implements java.io.Serializable {


     private Integer id;
     private ProjectEmployees projectEmployees;
     private ProjectTasks projectTasks;
     private Boolean isActive;
     private Date startDate;
     private Date endDate;

    public TaskAssignEmployees() {
    }

	
    public TaskAssignEmployees(ProjectEmployees projectEmployees, ProjectTasks projectTasks, Boolean isActive) {
        this.projectEmployees = projectEmployees;
        this.projectTasks = projectTasks;
        this.isActive = isActive;
    }
    public TaskAssignEmployees(ProjectEmployees projectEmployees, ProjectTasks projectTasks, Boolean isActive, Date startDate, Date endDate) {
       this.projectEmployees = projectEmployees;
       this.projectTasks = projectTasks;
       this.isActive = isActive;
       this.startDate = startDate;
       this.endDate = endDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ProjectEmployees getProjectEmployees() {
        return this.projectEmployees;
    }
    
    public void setProjectEmployees(ProjectEmployees projectEmployees) {
        this.projectEmployees = projectEmployees;
    }
    public ProjectTasks getProjectTasks() {
        return this.projectTasks;
    }
    
    public void setProjectTasks(ProjectTasks projectTasks) {
        this.projectTasks = projectTasks;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}


