package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UniversalPayrollManager generated by hbm2java
 */
public class UniversalPayrollManager  implements java.io.Serializable {


     private Integer id;
     private Employee employee;
     private GeneralUserProfile generalUserProfileByGeneralUserProfileGupIdAddedBy;
     private GeneralUserProfile generalUserProfileByGeneralUserProfileGupIdUpdatedBy;
     private Double basicSalary;
     private Double br;
     private Double noPay;
     private Double grossSalary;
     private Double epf8;
     private Double epf12;
     private Double attendance;
     private Double performance;
     private Double incentive;
     private Double travelling;
     private Double houseRental;
     private Double salaryAdvanced;
     private Double otherDeduction;
     private Double totalSalary;
     private Date salaryDate;
     private Date recordAddedDate;
     private Date lastUpdateTime;
     private double etf3;
     private double tax;

    public UniversalPayrollManager() {
    }

	
    public UniversalPayrollManager(Employee employee, GeneralUserProfile generalUserProfileByGeneralUserProfileGupIdAddedBy, double etf3, double tax) {
        this.employee = employee;
        this.generalUserProfileByGeneralUserProfileGupIdAddedBy = generalUserProfileByGeneralUserProfileGupIdAddedBy;
        this.etf3 = etf3;
        this.tax = tax;
    }
    public UniversalPayrollManager(Employee employee, GeneralUserProfile generalUserProfileByGeneralUserProfileGupIdAddedBy, GeneralUserProfile generalUserProfileByGeneralUserProfileGupIdUpdatedBy, Double basicSalary, Double br, Double noPay, Double grossSalary, Double epf8, Double epf12, Double attendance, Double performance, Double incentive, Double travelling, Double houseRental, Double salaryAdvanced, Double otherDeduction, Double totalSalary, Date salaryDate, Date recordAddedDate, Date lastUpdateTime, double etf3, double tax) {
       this.employee = employee;
       this.generalUserProfileByGeneralUserProfileGupIdAddedBy = generalUserProfileByGeneralUserProfileGupIdAddedBy;
       this.generalUserProfileByGeneralUserProfileGupIdUpdatedBy = generalUserProfileByGeneralUserProfileGupIdUpdatedBy;
       this.basicSalary = basicSalary;
       this.br = br;
       this.noPay = noPay;
       this.grossSalary = grossSalary;
       this.epf8 = epf8;
       this.epf12 = epf12;
       this.attendance = attendance;
       this.performance = performance;
       this.incentive = incentive;
       this.travelling = travelling;
       this.houseRental = houseRental;
       this.salaryAdvanced = salaryAdvanced;
       this.otherDeduction = otherDeduction;
       this.totalSalary = totalSalary;
       this.salaryDate = salaryDate;
       this.recordAddedDate = recordAddedDate;
       this.lastUpdateTime = lastUpdateTime;
       this.etf3 = etf3;
       this.tax = tax;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public GeneralUserProfile getGeneralUserProfileByGeneralUserProfileGupIdAddedBy() {
        return this.generalUserProfileByGeneralUserProfileGupIdAddedBy;
    }
    
    public void setGeneralUserProfileByGeneralUserProfileGupIdAddedBy(GeneralUserProfile generalUserProfileByGeneralUserProfileGupIdAddedBy) {
        this.generalUserProfileByGeneralUserProfileGupIdAddedBy = generalUserProfileByGeneralUserProfileGupIdAddedBy;
    }
    public GeneralUserProfile getGeneralUserProfileByGeneralUserProfileGupIdUpdatedBy() {
        return this.generalUserProfileByGeneralUserProfileGupIdUpdatedBy;
    }
    
    public void setGeneralUserProfileByGeneralUserProfileGupIdUpdatedBy(GeneralUserProfile generalUserProfileByGeneralUserProfileGupIdUpdatedBy) {
        this.generalUserProfileByGeneralUserProfileGupIdUpdatedBy = generalUserProfileByGeneralUserProfileGupIdUpdatedBy;
    }
    public Double getBasicSalary() {
        return this.basicSalary;
    }
    
    public void setBasicSalary(Double basicSalary) {
        this.basicSalary = basicSalary;
    }
    public Double getBr() {
        return this.br;
    }
    
    public void setBr(Double br) {
        this.br = br;
    }
    public Double getNoPay() {
        return this.noPay;
    }
    
    public void setNoPay(Double noPay) {
        this.noPay = noPay;
    }
    public Double getGrossSalary() {
        return this.grossSalary;
    }
    
    public void setGrossSalary(Double grossSalary) {
        this.grossSalary = grossSalary;
    }
    public Double getEpf8() {
        return this.epf8;
    }
    
    public void setEpf8(Double epf8) {
        this.epf8 = epf8;
    }
    public Double getEpf12() {
        return this.epf12;
    }
    
    public void setEpf12(Double epf12) {
        this.epf12 = epf12;
    }
    public Double getAttendance() {
        return this.attendance;
    }
    
    public void setAttendance(Double attendance) {
        this.attendance = attendance;
    }
    public Double getPerformance() {
        return this.performance;
    }
    
    public void setPerformance(Double performance) {
        this.performance = performance;
    }
    public Double getIncentive() {
        return this.incentive;
    }
    
    public void setIncentive(Double incentive) {
        this.incentive = incentive;
    }
    public Double getTravelling() {
        return this.travelling;
    }
    
    public void setTravelling(Double travelling) {
        this.travelling = travelling;
    }
    public Double getHouseRental() {
        return this.houseRental;
    }
    
    public void setHouseRental(Double houseRental) {
        this.houseRental = houseRental;
    }
    public Double getSalaryAdvanced() {
        return this.salaryAdvanced;
    }
    
    public void setSalaryAdvanced(Double salaryAdvanced) {
        this.salaryAdvanced = salaryAdvanced;
    }
    public Double getOtherDeduction() {
        return this.otherDeduction;
    }
    
    public void setOtherDeduction(Double otherDeduction) {
        this.otherDeduction = otherDeduction;
    }
    public Double getTotalSalary() {
        return this.totalSalary;
    }
    
    public void setTotalSalary(Double totalSalary) {
        this.totalSalary = totalSalary;
    }
    public Date getSalaryDate() {
        return this.salaryDate;
    }
    
    public void setSalaryDate(Date salaryDate) {
        this.salaryDate = salaryDate;
    }
    public Date getRecordAddedDate() {
        return this.recordAddedDate;
    }
    
    public void setRecordAddedDate(Date recordAddedDate) {
        this.recordAddedDate = recordAddedDate;
    }
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }
    
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
    public double getEtf3() {
        return this.etf3;
    }
    
    public void setEtf3(double etf3) {
        this.etf3 = etf3;
    }
    public double getTax() {
        return this.tax;
    }
    
    public void setTax(double tax) {
        this.tax = tax;
    }




}


