package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1



/**
 * UserLoginHasSystemInterface generated by hbm2java
 */
public class UserLoginHasSystemInterface  implements java.io.Serializable {


     private Integer id;
     private SystemInterface systemInterface;
     private UserLogin userLogin;

    public UserLoginHasSystemInterface() {
    }

    public UserLoginHasSystemInterface(SystemInterface systemInterface, UserLogin userLogin) {
       this.systemInterface = systemInterface;
       this.userLogin = userLogin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SystemInterface getSystemInterface() {
        return this.systemInterface;
    }
    
    public void setSystemInterface(SystemInterface systemInterface) {
        this.systemInterface = systemInterface;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }




}


