package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserCredentials generated by hbm2java
 */
public class UserCredentials  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile generalUserProfile;
     private Projects projects;
     private UserCredentialCategory userCredentialCategory;
     private UserCredentialType userCredentialType;
     private String username;
     private String password;
     private Date enteredDate;
     private String note;
     private Boolean isActive;
     private Set userCredentialIssuingManagers = new HashSet(0);
     private Set userCredentialHistories = new HashSet(0);
     private Set userCredentialRoles = new HashSet(0);

    public UserCredentials() {
    }

	
    public UserCredentials(GeneralUserProfile generalUserProfile, Projects projects, UserCredentialCategory userCredentialCategory, UserCredentialType userCredentialType, String username, String password, Date enteredDate, String note, Boolean isActive) {
        this.generalUserProfile = generalUserProfile;
        this.projects = projects;
        this.userCredentialCategory = userCredentialCategory;
        this.userCredentialType = userCredentialType;
        this.username = username;
        this.password = password;
        this.enteredDate = enteredDate;
        this.note = note;
        this.isActive = isActive;
    }
    public UserCredentials(GeneralUserProfile generalUserProfile, Projects projects, UserCredentialCategory userCredentialCategory, UserCredentialType userCredentialType, String username, String password, Date enteredDate, String note, Boolean isActive, Set userCredentialIssuingManagers, Set userCredentialHistories, Set userCredentialRoles) {
       this.generalUserProfile = generalUserProfile;
       this.projects = projects;
       this.userCredentialCategory = userCredentialCategory;
       this.userCredentialType = userCredentialType;
       this.username = username;
       this.password = password;
       this.enteredDate = enteredDate;
       this.note = note;
       this.isActive = isActive;
       this.userCredentialIssuingManagers = userCredentialIssuingManagers;
       this.userCredentialHistories = userCredentialHistories;
       this.userCredentialRoles = userCredentialRoles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public Projects getProjects() {
        return this.projects;
    }
    
    public void setProjects(Projects projects) {
        this.projects = projects;
    }
    public UserCredentialCategory getUserCredentialCategory() {
        return this.userCredentialCategory;
    }
    
    public void setUserCredentialCategory(UserCredentialCategory userCredentialCategory) {
        this.userCredentialCategory = userCredentialCategory;
    }
    public UserCredentialType getUserCredentialType() {
        return this.userCredentialType;
    }
    
    public void setUserCredentialType(UserCredentialType userCredentialType) {
        this.userCredentialType = userCredentialType;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Set getUserCredentialIssuingManagers() {
        return this.userCredentialIssuingManagers;
    }
    
    public void setUserCredentialIssuingManagers(Set userCredentialIssuingManagers) {
        this.userCredentialIssuingManagers = userCredentialIssuingManagers;
    }
    public Set getUserCredentialHistories() {
        return this.userCredentialHistories;
    }
    
    public void setUserCredentialHistories(Set userCredentialHistories) {
        this.userCredentialHistories = userCredentialHistories;
    }
    public Set getUserCredentialRoles() {
        return this.userCredentialRoles;
    }
    
    public void setUserCredentialRoles(Set userCredentialRoles) {
        this.userCredentialRoles = userCredentialRoles;
    }




}


