package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserCredentialViewRequest generated by hbm2java
 */
public class UserCredentialViewRequest  implements java.io.Serializable {


     private Integer id;
     private UserCredentialIssuingManager userCredentialIssuingManager;
     private Date requestedDate;
     private Date approvedDate;
     private Boolean isActive;

    public UserCredentialViewRequest() {
    }

    public UserCredentialViewRequest(UserCredentialIssuingManager userCredentialIssuingManager, Date requestedDate, Date approvedDate , Boolean isActive) {
       this.userCredentialIssuingManager = userCredentialIssuingManager;
       this.requestedDate = requestedDate;
       this.approvedDate = approvedDate;
        this.isActive = isActive;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserCredentialIssuingManager getUserCredentialIssuingManager() {
        return this.userCredentialIssuingManager;
    }
    
    public void setUserCredentialIssuingManager(UserCredentialIssuingManager userCredentialIssuingManager) {
        this.userCredentialIssuingManager = userCredentialIssuingManager;
    }
    public Date getRequestedDate() {
        return this.requestedDate;
    }
    
    public void setRequestedDate(Date requestedDate) {
        this.requestedDate = requestedDate;
    }
    public Date getApprovedDate() {
        return this.approvedDate;
    }
    
    public void setApprovedDate(Date approvedDate) {
        this.approvedDate = approvedDate;
    }

    public Boolean getIsActive() {
        return isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }


}


