package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserCredentialType generated by hbm2java
 */
public class UserCredentialType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set userCredentialses = new HashSet(0);

    public UserCredentialType() {
    }

	
    public UserCredentialType(String name) {
        this.name = name;
    }
    public UserCredentialType(String name, Set userCredentialses) {
       this.name = name;
       this.userCredentialses = userCredentialses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserCredentialses() {
        return this.userCredentialses;
    }
    
    public void setUserCredentialses(Set userCredentialses) {
        this.userCredentialses = userCredentialses;
    }




}


