package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserCredentialIssuingManager generated by hbm2java
 */
public class UserCredentialIssuingManager  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile generalUserProfile;
     private UserCredentials userCredentials;
     private Date issueDate;
     private Boolean isActive;
     private Boolean isChanged;
     private Boolean isResigned;
     private Date changedDate;
     private Boolean firstTimeViewed;
     private Set userCredentialViewRequests = new HashSet(0);

    public UserCredentialIssuingManager() {
    }

	
    public UserCredentialIssuingManager(GeneralUserProfile generalUserProfile, UserCredentials userCredentials, Date issueDate, Boolean isActive, Boolean isChanged, Boolean isResigned, Date changedDate, Boolean firstTimeViewed) {
        this.generalUserProfile = generalUserProfile;
        this.userCredentials = userCredentials;
        this.issueDate = issueDate;
        this.isActive = isActive;
        this.isChanged = isChanged;
        this.isResigned = isResigned;
        this.changedDate = changedDate;
        this.firstTimeViewed = firstTimeViewed;
    }
    public UserCredentialIssuingManager(GeneralUserProfile generalUserProfile, UserCredentials userCredentials, Date issueDate, Boolean isActive, Boolean isChanged, Boolean isResigned, Date changedDate, Boolean firstTimeViewed, Set userCredentialViewRequests) {
       this.generalUserProfile = generalUserProfile;
       this.userCredentials = userCredentials;
       this.issueDate = issueDate;
       this.isActive = isActive;
       this.isChanged = isChanged;
       this.isResigned = isResigned;
       this.changedDate = changedDate;
       this.firstTimeViewed = firstTimeViewed;
       this.userCredentialViewRequests = userCredentialViewRequests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public UserCredentials getUserCredentials() {
        return this.userCredentials;
    }
    
    public void setUserCredentials(UserCredentials userCredentials) {
        this.userCredentials = userCredentials;
    }
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Boolean getIsChanged() {
        return this.isChanged;
    }
    
    public void setIsChanged(Boolean isChanged) {
        this.isChanged = isChanged;
    }
    public Boolean getIsResigned() {
        return this.isResigned;
    }
    
    public void setIsResigned(Boolean isResigned) {
        this.isResigned = isResigned;
    }
    public Date getChangedDate() {
        return this.changedDate;
    }
    
    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }
    public Boolean getFirstTimeViewed() {
        return this.firstTimeViewed;
    }
    
    public void setFirstTimeViewed(Boolean firstTimeViewed) {
        this.firstTimeViewed = firstTimeViewed;
    }
    public Set getUserCredentialViewRequests() {
        return this.userCredentialViewRequests;
    }
    
    public void setUserCredentialViewRequests(Set userCredentialViewRequests) {
        this.userCredentialViewRequests = userCredentialViewRequests;
    }




}


