package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1



/**
 * UserCredentialRole generated by hbm2java
 */
public class UserCredentialRole  implements java.io.Serializable {


     private Integer id;
     private CredentialRoles credentialRoles;
     private UserCredentials userCredentials;

    public UserCredentialRole() {
    }

    public UserCredentialRole(CredentialRoles credentialRoles, UserCredentials userCredentials) {
       this.credentialRoles = credentialRoles;
       this.userCredentials = userCredentials;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CredentialRoles getCredentialRoles() {
        return this.credentialRoles;
    }
    
    public void setCredentialRoles(CredentialRoles credentialRoles) {
        this.credentialRoles = credentialRoles;
    }
    public UserCredentials getUserCredentials() {
        return this.userCredentials;
    }
    
    public void setUserCredentials(UserCredentials userCredentials) {
        this.userCredentials = userCredentials;
    }




}


