package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserCredentialViewRequestType generated by hbm2java
 */
public class UserCredentialViewRequestType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set userCredentialViewRequests = new HashSet(0);

    public UserCredentialViewRequestType() {
    }

	
    public UserCredentialViewRequestType(String name) {
        this.name = name;
    }
    public UserCredentialViewRequestType(String name, Set userCredentialViewRequests) {
       this.name = name;
       this.userCredentialViewRequests = userCredentialViewRequests;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserCredentialViewRequests() {
        return this.userCredentialViewRequests;
    }
    
    public void setUserCredentialViewRequests(Set userCredentialViewRequests) {
        this.userCredentialViewRequests = userCredentialViewRequests;
    }




}


