package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile generalUserProfile;
     private UserRole userRole;
     private String username;
     private String password;
     private Integer maxLoginAttemp;
     private Integer countAttempt;
     private Boolean isActive;
     private Set helpTickets = new HashSet(0);
     private Set loginSessions = new HashSet(0);
     private Set userLoginHasSystemInterfaces = new HashSet(0);

    public UserLogin() {
    }

	
    public UserLogin(GeneralUserProfile generalUserProfile, UserRole userRole) {
        this.generalUserProfile = generalUserProfile;
        this.userRole = userRole;
    }
    public UserLogin(GeneralUserProfile generalUserProfile, UserRole userRole, String username, String password, Integer maxLoginAttemp, Integer countAttempt, Boolean isActive, Set helpTickets, Set loginSessions, Set userLoginHasSystemInterfaces) {
       this.generalUserProfile = generalUserProfile;
       this.userRole = userRole;
       this.username = username;
       this.password = password;
       this.maxLoginAttemp = maxLoginAttemp;
       this.countAttempt = countAttempt;
       this.isActive = isActive;
       this.helpTickets = helpTickets;
       this.loginSessions = loginSessions;
       this.userLoginHasSystemInterfaces = userLoginHasSystemInterfaces;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getMaxLoginAttemp() {
        return this.maxLoginAttemp;
    }
    
    public void setMaxLoginAttemp(Integer maxLoginAttemp) {
        this.maxLoginAttemp = maxLoginAttemp;
    }
    public Integer getCountAttempt() {
        return this.countAttempt;
    }
    
    public void setCountAttempt(Integer countAttempt) {
        this.countAttempt = countAttempt;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Set getHelpTickets() {
        return this.helpTickets;
    }
    
    public void setHelpTickets(Set helpTickets) {
        this.helpTickets = helpTickets;
    }
    public Set getLoginSessions() {
        return this.loginSessions;
    }
    
    public void setLoginSessions(Set loginSessions) {
        this.loginSessions = loginSessions;
    }
    public Set getUserLoginHasSystemInterfaces() {
        return this.userLoginHasSystemInterfaces;
    }
    
    public void setUserLoginHasSystemInterfaces(Set userLoginHasSystemInterfaces) {
        this.userLoginHasSystemInterfaces = userLoginHasSystemInterfaces;
    }




}


