package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set userRoleHasSystemInterfaces = new HashSet(0);
     private Set userLogins = new HashSet(0);

    public UserRole() {
    }

    public UserRole(String name, Set userRoleHasSystemInterfaces, Set userLogins) {
       this.name = name;
       this.userRoleHasSystemInterfaces = userRoleHasSystemInterfaces;
       this.userLogins = userLogins;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUserRoleHasSystemInterfaces() {
        return this.userRoleHasSystemInterfaces;
    }
    
    public void setUserRoleHasSystemInterfaces(Set userRoleHasSystemInterfaces) {
        this.userRoleHasSystemInterfaces = userRoleHasSystemInterfaces;
    }
    public Set getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set userLogins) {
        this.userLogins = userLogins;
    }




}


