package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserCredentialHistory generated by hbm2java
 */
public class UserCredentialHistory  implements java.io.Serializable {


     private Integer id;
     private GeneralUserProfile generalUserProfile;
     private UserCredentials userCredentials;
     private String username;
     private String password;
     private Date updatedDate;
     private String reason;

    public UserCredentialHistory() {
    }

    public UserCredentialHistory(GeneralUserProfile generalUserProfile, UserCredentials userCredentials, String username, String password, Date updatedDate, String reason) {
       this.generalUserProfile = generalUserProfile;
       this.userCredentials = userCredentials;
       this.username = username;
       this.password = password;
       this.updatedDate = updatedDate;
       this.reason = reason;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public UserCredentials getUserCredentials() {
        return this.userCredentials;
    }
    
    public void setUserCredentials(UserCredentials userCredentials) {
        this.userCredentials = userCredentials;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }




}


