package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1



/**
 * UserRoleHasSystemInterface generated by hbm2java
 */
public class UserRoleHasSystemInterface  implements java.io.Serializable {


     private Integer id;
     private SystemInterface systemInterface;
     private UserRole userRole;

    public UserRoleHasSystemInterface() {
    }

    public UserRoleHasSystemInterface(SystemInterface systemInterface, UserRole userRole) {
       this.systemInterface = systemInterface;
       this.userRole = userRole;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SystemInterface getSystemInterface() {
        return this.systemInterface;
    }
    
    public void setSystemInterface(SystemInterface systemInterface) {
        this.systemInterface = systemInterface;
    }
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }




}


