package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Voucher generated by hbm2java
 */
public class Voucher  implements java.io.Serializable {


     private Integer id;
     private GeneralOrganizationProfile generalOrganizationProfile;
     private GeneralUserProfile generalUserProfile;
     private LoginSession loginSession;
     private PaymentMode paymentMode;
     private VoucherType voucherType;
     private String vid;
     private Double voucherTotal;
     private Date date;
     private Boolean isActive;
     private String description;
     private Date paymentDate;

    public Voucher() {
    }

	
    public Voucher(GeneralOrganizationProfile generalOrganizationProfile, GeneralUserProfile generalUserProfile, PaymentMode paymentMode, VoucherType voucherType, Date paymentDate) {
        this.generalOrganizationProfile = generalOrganizationProfile;
        this.generalUserProfile = generalUserProfile;
        this.paymentMode = paymentMode;
        this.voucherType = voucherType;
        this.paymentDate = paymentDate;
    }
    public Voucher(GeneralOrganizationProfile generalOrganizationProfile, GeneralUserProfile generalUserProfile, LoginSession loginSession, PaymentMode paymentMode, VoucherType voucherType, String vid, Double voucherTotal, Date date, Boolean isActive, String description, Date paymentDate) {
       this.generalOrganizationProfile = generalOrganizationProfile;
       this.generalUserProfile = generalUserProfile;
       this.loginSession = loginSession;
       this.paymentMode = paymentMode;
       this.voucherType = voucherType;
       this.vid = vid;
       this.voucherTotal = voucherTotal;
       this.date = date;
       this.isActive = isActive;
       this.description = description;
       this.paymentDate = paymentDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GeneralOrganizationProfile getGeneralOrganizationProfile() {
        return this.generalOrganizationProfile;
    }
    
    public void setGeneralOrganizationProfile(GeneralOrganizationProfile generalOrganizationProfile) {
        this.generalOrganizationProfile = generalOrganizationProfile;
    }
    public GeneralUserProfile getGeneralUserProfile() {
        return this.generalUserProfile;
    }
    
    public void setGeneralUserProfile(GeneralUserProfile generalUserProfile) {
        this.generalUserProfile = generalUserProfile;
    }
    public LoginSession getLoginSession() {
        return this.loginSession;
    }
    
    public void setLoginSession(LoginSession loginSession) {
        this.loginSession = loginSession;
    }
    public PaymentMode getPaymentMode() {
        return this.paymentMode;
    }
    
    public void setPaymentMode(PaymentMode paymentMode) {
        this.paymentMode = paymentMode;
    }
    public VoucherType getVoucherType() {
        return this.voucherType;
    }
    
    public void setVoucherType(VoucherType voucherType) {
        this.voucherType = voucherType;
    }
    public String getVid() {
        return this.vid;
    }
    
    public void setVid(String vid) {
        this.vid = vid;
    }
    public Double getVoucherTotal() {
        return this.voucherTotal;
    }
    
    public void setVoucherTotal(Double voucherTotal) {
        this.voucherTotal = voucherTotal;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }




}


