package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VoucherType generated by hbm2java
 */
public class VoucherType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String abbreviation;
     private Set vouchers = new HashSet(0);

    public VoucherType() {
    }

    public VoucherType(String name, String abbreviation, Set vouchers) {
       this.name = name;
       this.abbreviation = abbreviation;
       this.vouchers = vouchers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAbbreviation() {
        return this.abbreviation;
    }
    
    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }
    public Set getVouchers() {
        return this.vouchers;
    }
    
    public void setVouchers(Set vouchers) {
        this.vouchers = vouchers;
    }




}


