package Model.Mapping;
// Generated Dec 8, 2023 10:58:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * WorkHistory generated by hbm2java
 */
public class WorkHistory  implements java.io.Serializable {


     private Integer id;
     private Designation designationByDesignationFrom;
     private Designation designationByDesignationTo;
     private Employee employee;
     private Date dateFrom;
     private Date dateTo;

    public WorkHistory() {
    }

	
    public WorkHistory(Designation designationByDesignationFrom, Employee employee) {
        this.designationByDesignationFrom = designationByDesignationFrom;
        this.employee = employee;
    }
    public WorkHistory(Designation designationByDesignationFrom, Designation designationByDesignationTo, Employee employee, Date dateFrom, Date dateTo) {
       this.designationByDesignationFrom = designationByDesignationFrom;
       this.designationByDesignationTo = designationByDesignationTo;
       this.employee = employee;
       this.dateFrom = dateFrom;
       this.dateTo = dateTo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Designation getDesignationByDesignationFrom() {
        return this.designationByDesignationFrom;
    }
    
    public void setDesignationByDesignationFrom(Designation designationByDesignationFrom) {
        this.designationByDesignationFrom = designationByDesignationFrom;
    }
    public Designation getDesignationByDesignationTo() {
        return this.designationByDesignationTo;
    }
    
    public void setDesignationByDesignationTo(Designation designationByDesignationTo) {
        this.designationByDesignationTo = designationByDesignationTo;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Date getDateFrom() {
        return this.dateFrom;
    }
    
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }
    public Date getDateTo() {
        return this.dateTo;
    }
    
    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }




}


